In [ ]:
import pandas as pd
import glob

files = glob.glob('/content/*.csv')

print("Jumlah file:", len(files))

Jumlah file: 7

In [ ]:
df = pd.read_csv("penumpang_bandara_2019.csv")

In [ ]:
# Ambil header penting
kategori = pd.Series(df.iloc[1].values).ffill().values
bulan = df.iloc[3].values

# Buang header
df = df.iloc[4:].reset_index(drop=True)

df.head()

,Bandara Utama Domestik,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39
0,Kualanamu-Medan,280839,198871,202298,195395,155731,245820,236009,225363,214364,...,22119,16822,22560,27014,26587,20680,24742,23537,25834,280503
1,Soekarno Hatta-Jakarta,1569630,1427000,1538314,1403186,1276006,1568669,1749777,1714643,1630312,...,38903,42042,60663,61424,41870,28787,52914,54212,53853,556317
2,Juanda-Surabaya,560242,473070,481147,443457,378933,607024,620237,541273,516321,...,55470,54457,52710,71074,81665,76985,79792,81769,77417,819228
3,Hasanudin-Makassar,299845,242539,261757,246228,221716,306475,307516,291482,289609,...,153915,161119,178546,202310,190389,182261,188053,195082,190282,2153778
4,Ngurah Rai-Bali,428629,357076,369930,364220,289400,460273,459284,480603,424781,...,27255,27603,38380,35495,30794,31747,34961,33990,30433,352471

In [ ]:
# Rename kolom pertama
df = df.rename(columns={df.columns[0]: "Bandara"})

# Samakan panjang
kategori = kategori[:len(df.columns)]
bulan = bulan[:len(df.columns)]

# Buang kolom Tahunan
mask = [b != "Tahunan" for b in bulan]

df = df.loc[:, mask]
kategori = kategori[mask]
bulan = bulan[mask]

# Buat nama kolom
kolom_baru = ["Bandara"]

for k, b in zip(kategori[1:], bulan[1:]):
    kolom_baru.append(f"{k}_{b}")

df.columns = kolom_baru

df.head()

,Bandara,Keberangkatan_Januari,Keberangkatan_Februari,Keberangkatan_Maret,Keberangkatan_April,Keberangkatan_Mei,Keberangkatan_Juni,Keberangkatan_Juli,Keberangkatan_Agustus,Keberangkatan_September,...,Transit_Maret,Transit_April,Transit_Mei,Transit_Juni,Transit_Juli,Transit_Agustus,Transit_September,Transit_Oktober,Transit_November,Transit_Desember
0,Kualanamu-Medan,280839,198871,202298,195395,155731,245820,236009,225363,214364,...,24417,22119,16822,22560,27014,26587,20680,24742,23537,25834
1,Soekarno Hatta-Jakarta,1569630,1427000,1538314,1403186,1276006,1568669,1749777,1714643,1630312,...,40472,38903,42042,60663,61424,41870,28787,52914,54212,53853
2,Juanda-Surabaya,560242,473070,481147,443457,378933,607024,620237,541273,516321,...,64527,55470,54457,52710,71074,81665,76985,79792,81769,77417
3,Hasanudin-Makassar,299845,242539,261757,246228,221716,306475,307516,291482,289609,...,173459,153915,161119,178546,202310,190389,182261,188053,195082,190282
4,Ngurah Rai-Bali,428629,357076,369930,364220,289400,460273,459284,480603,424781,...,29718,27255,27603,38380,35495,30794,31747,34961,33990,30433

In [ ]:
# Ambil hanya 5 bandara utama
bandara_utama = [
    "Kualanamu-Medan",
    "Soekarno Hatta-Jakarta",
    "Juanda-Surabaya",
    "Hasanudin-Makassar",
    "Ngurah Rai-Bali"
]

df = df[df["Bandara"].isin(bandara_utama)]

# Tambah tahun
df["Tahun"] = 2019

df.head()

,Bandara,Keberangkatan_Januari,Keberangkatan_Februari,Keberangkatan_Maret,Keberangkatan_April,Keberangkatan_Mei,Keberangkatan_Juni,Keberangkatan_Juli,Keberangkatan_Agustus,Keberangkatan_September,...,Transit_April,Transit_Mei,Transit_Juni,Transit_Juli,Transit_Agustus,Transit_September,Transit_Oktober,Transit_November,Transit_Desember,Tahun
0,Kualanamu-Medan,280839,198871,202298,195395,155731,245820,236009,225363,214364,...,22119,16822,22560,27014,26587,20680,24742,23537,25834,2019
1,Soekarno Hatta-Jakarta,1569630,1427000,1538314,1403186,1276006,1568669,1749777,1714643,1630312,...,38903,42042,60663,61424,41870,28787,52914,54212,53853,2019
2,Juanda-Surabaya,560242,473070,481147,443457,378933,607024,620237,541273,516321,...,55470,54457,52710,71074,81665,76985,79792,81769,77417,2019
3,Hasanudin-Makassar,299845,242539,261757,246228,221716,306475,307516,291482,289609,...,153915,161119,178546,202310,190389,182261,188053,195082,190282,2019
4,Ngurah Rai-Bali,428629,357076,369930,364220,289400,460273,459284,480603,424781,...,27255,27603,38380,35495,30794,31747,34961,33990,30433,2019

In [ ]:
def preprocess(df, tahun):

    # Ambil header penting
    kategori = pd.Series(df.iloc[1].values).ffill().values
    bulan = df.iloc[3].values

    # Buang header
    df = df.iloc[4:].reset_index(drop=True)

    # Rename kolom pertama
    df = df.rename(columns={df.columns[0]: "Bandara"})

    # Samakan panjang
    kategori = kategori[:len(df.columns)]
    bulan = bulan[:len(df.columns)]

    # Buang kolom Tahunan
    mask = [b != "Tahunan" for b in bulan]

    df = df.loc[:, mask]
    kategori = kategori[mask]
    bulan = bulan[mask]

    # Buat nama kolom
    kolom_baru = ["Bandara"]

    for k, b in zip(kategori[1:], bulan[1:]):
        kolom_baru.append(f"{k}_{b}")

    df.columns = kolom_baru

    # Ambil hanya 5 bandara utama
    bandara_utama = [
        "Kualanamu-Medan",
        "Soekarno Hatta-Jakarta",
        "Juanda-Surabaya",
        "Hasanudin-Makassar",
        "Ngurah Rai-Bali"
    ]

    df = df[df["Bandara"].isin(bandara_utama)]

    # Tambah tahun
    df["Tahun"] = tahun

    return df

In [ ]:
# GABUNG SEMUA TAHUN
all_data = []

for tahun in range(2019, 2026):

    file = f"penumpang_bandara_{tahun}.csv"

    df = pd.read_csv(file)

    df = preprocess(df, tahun)

    all_data.append(df)

# SATUKAN
final_df = pd.concat(all_data, ignore_index=True)

final_df.head()

,Bandara,Keberangkatan_Januari,Keberangkatan_Februari,Keberangkatan_Maret,Keberangkatan_April,Keberangkatan_Mei,Keberangkatan_Juni,Keberangkatan_Juli,Keberangkatan_Agustus,Keberangkatan_September,...,Transit_April,Transit_Mei,Transit_Juni,Transit_Juli,Transit_Agustus,Transit_September,Transit_Oktober,Transit_November,Transit_Desember,Tahun
0,Kualanamu-Medan,280839,198871,202298,195395,155731,245820,236009,225363,214364,...,22119,16822,22560,27014,26587,20680,24742,23537,25834,2019
1,Soekarno Hatta-Jakarta,1569630,1427000,1538314,1403186,1276006,1568669,1749777,1714643,1630312,...,38903,42042,60663,61424,41870,28787,52914,54212,53853,2019
2,Juanda-Surabaya,560242,473070,481147,443457,378933,607024,620237,541273,516321,...,55470,54457,52710,71074,81665,76985,79792,81769,77417,2019
3,Hasanudin-Makassar,299845,242539,261757,246228,221716,306475,307516,291482,289609,...,153915,161119,178546,202310,190389,182261,188053,195082,190282,2019
4,Ngurah Rai-Bali,428629,357076,369930,364220,289400,460273,459284,480603,424781,...,27255,27603,38380,35495,30794,31747,34961,33990,30433,2019

In [ ]:
final_df["Tahun"].unique()

final_df.shape

(35, 38)

In [ ]:
pd.set_option('display.max_columns', None)

print(final_df.head())

                  Bandara Keberangkatan_Januari Keberangkatan_Februari  \
0         Kualanamu-Medan                280839                 198871
1  Soekarno Hatta-Jakarta               1569630                1427000
2         Juanda-Surabaya                560242                 473070
3      Hasanudin-Makassar                299845                 242539
4         Ngurah Rai-Bali                428629                 357076

  Keberangkatan_Maret Keberangkatan_April Keberangkatan_Mei  \
0              202298              195395            155731
1             1538314             1403186           1276006
2              481147              443457            378933
3              261757              246228            221716
4              369930              364220            289400

  Keberangkatan_Juni Keberangkatan_Juli Keberangkatan_Agustus  \
0             245820             236009                225363
1            1568669            1749777               1714643
2             607024             620237                541273
3             306475             307516                291482
4             460273             459284                480603

  Keberangkatan_September Keberangkatan_Oktober Keberangkatan_November  \
0                  214364                225484                 229847
1                 1630312               1738571                1778862
2                  516321                543876                 549010
3                  289609                295343                 299358
4                  424781                435861                 435288

  Keberangkatan_Desember Kedatangan_Januari Kedatangan_Februari  \
0                 220846             260409              209554
1                1870092            1589946             1393713
2                 574001             609470              531172
3                 291897             409072              344573
4                 450458             377116              363919

  Kedatangan_Maret Kedatangan_April Kedatangan_Mei Kedatangan_Juni  \
0           239181           203173         196741          251732
1          1458751          1449256        1341301         1705536
2           548463           520438         537619          626041
3           394216           362586         353262          423338
4           368981           371964         295317          457417

  Kedatangan_Juli Kedatangan_Agustus Kedatangan_September Kedatangan_Oktober  \
0          253864             247912               232768             250395
1         1766005            1744969              1681603            1765701
2          604344             641729               576087             621606
3          437249             428627               426396             446677
4          454042             483918               418339             441304

  Kedatangan_November Kedatangan_Desember Transit_Januari Transit_Februari  \
0              253826              304154           27176            19015
1             1798426             1785044           39349            41828
2              632043              661927           70494            52868
3              448377              466452          185683           152679
4              433349              508853            2831            29264

  Transit_Maret Transit_April Transit_Mei Transit_Juni Transit_Juli  \
0         24417         22119       16822        22560        27014
1         40472         38903       42042        60663        61424
2         64527         55470       54457        52710        71074
3        173459        153915      161119       178546       202310
4         29718         27255       27603        38380        35495

  Transit_Agustus Transit_September Transit_Oktober Transit_November  \
0           26587             20680           24742            23537
1           41870             28787           52914            54212
2           81665             76985           79792            81769
3          190389            182261          188053           195082
4           30794             31747           34961            33990

  Transit_Desember  Tahun
0            25834   2019
1            53853   2019
2            77417   2019
3           190282   2019
4            30433   2019

In [ ]:
df_long = final_df.melt(
    id_vars=["Bandara", "Tahun"],
    var_name="Kategori_Bulan",
    value_name="Jumlah"
)

df_long[["Kategori", "Bulan"]] = df_long["Kategori_Bulan"].str.split("_", expand=True)

df_long = df_long.drop(columns=["Kategori_Bulan"])

df_long.head()

                  Bandara  Tahun   Jumlah       Kategori    Bulan
0         Kualanamu-Medan   2019   280839  Keberangkatan  Januari
1  Soekarno Hatta-Jakarta   2019  1569630  Keberangkatan  Januari
2         Juanda-Surabaya   2019   560242  Keberangkatan  Januari
3      Hasanudin-Makassar   2019   299845  Keberangkatan  Januari
4         Ngurah Rai-Bali   2019   428629  Keberangkatan  Januari

In [ ]:
df_pivot = df_long.pivot_table(
    index=["Bandara", "Tahun", "Bulan"],
    columns="Kategori",
    values="Jumlah",
    aggfunc="sum"
).reset_index()

df_pivot.head()

Kategori             Bandara  Tahun     Bulan Keberangkatan Kedatangan Transit
0         Hasanudin-Makassar   2019   Agustus        291482     428627  190389
1         Hasanudin-Makassar   2019     April        246228     362586  153915
2         Hasanudin-Makassar   2019  Desember        291897     466452  190282
3         Hasanudin-Makassar   2019  Februari        242539     344573  152679
4         Hasanudin-Makassar   2019   Januari        299845     409072  185683

In [ ]:
df_pivot.to_csv("data_pivot_bandara.csv", index=False)

In [ ]:
from google.colab import files

files.download("data_pivot_bandara.csv")